import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import locationsRouter from "./locations";
import categoriesRouter from "./categories";
import unitsRouter from "./units";
import shelvesRouter from "./shelves";
import inventoryRouter from "./inventory";
import transactionsRouter from "./transactions";
import shiftsRouter from "./shifts";
import transfersRouter from "./transfers";
import analyticsRouter from "./analytics";
import momoRouter from "./momo";
import seedRouter from "./seed";
import settingsRouter from "./settings";
import auditRouter from "./audit";
import usersRouter from "./users";
import salesLogsRouter from "./sales-logs";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/locations", locationsRouter);
router.use("/categories", categoriesRouter);
router.use("/units", unitsRouter);
router.use("/shelves", shelvesRouter);
router.use("/inventory", inventoryRouter);
router.use("/transactions", transactionsRouter);
router.use("/shifts", shiftsRouter);
router.use("/transfers", transfersRouter);
router.use("/analytics", analyticsRouter);
router.use("/momo", momoRouter);
router.use("/seed", seedRouter);
router.use("/settings", settingsRouter);
router.use("/audit", auditRouter);
router.use("/users", usersRouter);
router.use("/sales-logs", salesLogsRouter);

export default router;
